{% set data = load_setuptools() %}

package:
    name: conda-testenv
    version: {{data.get('version')}}

source:
    path: ../

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        - setuptools
        - conda
        - conda-build

test:
    imports:
        - conda_testenv
    commands:
        - conda-testenv --help
        - conda testenv --help

about:
    license: BSD-3
    home: https://github.com/SciTools/conda-testenv
